services:
  compiler:
    image: aleixmt/bmde-linux:latest
    container_name: compiler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/input/filesystem-nds
    entrypoint: sh -c "cd /input/filesystem-nds && make clean && make && dlditool /bmde/dlditool/mpcf.dldi /input/filesystem-nds/filesystem-nds.nds"
    user: 1000:1000

  runner-cli:
    image: aleixmt/desmume-cli:latest
    container_name: runner-cli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/roms/
      - ./fs:/fs
    depends_on:
      - compiler
    # apt-get update && apt-get install -y unzip && unzip /fs/fat.zip &&
    entrypoint: sh -c "desmume-cli /roms/filesystem-nds.nds --disable-sound --cflash-image /fs/fat.img"

  watchdog:
    image: aleixmt/desmume-watchdog:latest
    container_name: watchdog
    build:
      context: .
      dockerfile: watchdog.Dockerfile
    volumes:
      - ./fs:/fs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - runner-cli
    restart: "no"
    privileged: true




