services:
  bmde-linux:
    image: aleixmt/bmde-linux:latest
    #build: .  # Uncomment to use Dockerfile to extend base image
    volumes:
     - ../:/input/  # Makefile expected in the same directory as this compose file.
                    # Output binaries will have the same name as project folder name  .
